src/Entity/Chambre.php
<?php

namespace App\Entity;

use App\Repository\ChambreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ChambreRepository::class)
 */
class Chambre
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $numero;

    /**
     * @ORM\Column(type="string", length=15)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $numero_batimat;

   
    public function __construct()
    {
        $this->etudiants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumero(): ?string
    {
        return $this->numero;
    }

    public function setNumero(string $numero): self
    {
        $this->numero = $numero;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getNumeroBatimat(): ?string
    {
        return $this->numero_batimat;
    }

    public function setNumeroBatimat(string $numero_batimat): self
    {
        $this->numero_batimat = $numero_batimat;

        return $this;
    }

    // public function getEtudiant(): ?Etudiant
    // {
    //     return $this->etudiant;
    // }

    // public function setEtudiant(?Etudiant $etudiant): self
    // {
    //     $this->etudiant = $etudiant;

    //     return $this;
    // }

    // /**
    //  * @return Collection|Etudiant[]
    //  */
    // public function getEtudiants(): Collection
    // {
    //     return $this->etudiants;
    // }

    // public function addEtudiant(Etudiant $etudiant): self
    // {
    //     if (!$this->etudiants->contains($etudiant)) {
    //         $this->etudiants[] = $etudiant;
    //         $etudiant->setChambre($this);
    //     }

    //     return $this;
    // }

    // public function removeEtudiant(Etudiant $etudiant): self
    // {
    //     if ($this->etudiants->contains($etudiant)) {
    //         $this->etudiants->removeElement($etudiant);
    //         // set the owning side to null (unless already changed)
    //         if ($etudiant->getChambre() === $this) {
    //             $etudiant->setChambre(null);
    //         }
    //     }

    //     return $this;
    // }
}

src/Form/ChambreType.php
<?php

namespace App\Form;

use App\Entity\Chambre;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ChambreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('type',ChoiceType::class,[
                'choices' => [
                    'Choisir une class'=> null,
                    'Individuel'=> "individuel",
                    'Double' => 'double',
                ],
            ])
            ->add('numero_batimat')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Chambre::class,
        ]);
    }
}

src/Controller/ChambreController.php
<?php

namespace App\Controller;

use App\Entity\Chambre;
use App\Form\ChambreType;
use App\Repository\ChambreRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\SerializerInterface;

/**
 * @Route("/chambre")
 */
class ChambreController extends AbstractController
{
    /**
     * @Route("/", name="chambre")
     */
    public function index(ChambreRepository $chambreRepository)
    {
        $chambre = $chambreRepository->findAll();
        return $this->render('chambre/index.html.twig', compact('chambre'),);
    }
    
    /**
     * @Route("/add", name="addChambre", methods={"POST","GET"})
     */
    public function add(Request $request, ChambreRepository $cham):Response
    {
        

        $chambre = new Chambre();
        $form = $this->createForm(ChambreType::class,$chambre);
        if($request->isMethod('POST'))
        {
            if($request->isXmlHttpRequest())
            {
                $form->handleRequest($request);
                //return new JsonResponse(['profil'  => json_encode($request->request->all())]);
                if($form->isSubmitted() && $form->isValid())
                {
                    //dd($chambre);
                    //$numbat=$form->get('numero_batimat')->getData();
                    // $idLast = $cham->findBy(array(),array('id' => 'DESC'),1 ,0);
                    // $idLast=$idLast[0];
                    $idLast = sprintf("%'.03d", rand(0,999));
                    $numBat=$form->get('numero_batimat')->getData();
                  
                   $gen=new Generator();
                    $numCham=$gen->generateNumeroChambre($idLast,$numBat);


                    $chambre->setNumero($numCham);
                    
                    $em = $this->getDoctrine()->getManager();
                    $em->persist($chambre);
                    $em->flush();
                    return new JsonResponse(['resultat'  => json_encode("success")]);
                   
                   //return $this->redirectToRoute('listChambre');
                }
                
                // //dump($form);

            }else
            {
                //dump($form);
                return new Response('Bad request',400);
            }
        }
        
        return $this->render('Chambre/edit.html.twig', [
            'form' => $form->createView()
        ]);
    }
    /**
     * @Route("/list", name="listChambre")
     */
    public function list(ChambreRepository $chambreRepository)
    {
        $chambre = $chambreRepository->findAll();
       // dd($chambre);
        return $this->render('Chambre/index.html.twig', compact(('chambre')));
    }

    /**
     * @Route("/getlist/{p<[0-9]+>}", name="getChambre", defaults={"p"=1})
     */
    public function getChambreList(ChambreRepository $chambreRepository,SerializerInterface $serializer, $p)
    {
       // $chambre = $chambreRepository->findAll();

        
        // le nombre total de pages !
       $nbrePage =ceil(count($chambreRepository->findAll())/3);
       // Pgae encours $p
       $offset=  3*($p-1);
        $chambre =$chambreRepository->findBy(
            array(),
            array('id' => 'DESC'),
            3,//limit
            $offset//offset
        );

        $cham_serialize = $serializer->serialize($chambre, 'json');
       // dd($chambre);

      return new JsonResponse(json_encode(['chambre'=>$cham_serialize,'nbrPage'=>$nbrePage]), 200, [], true);
       
       // return $this->render('Chambre/index.html.twig', compact(('chambre')));
    }

    /**
     * @Route("/{id<[0-9]+>}/update", name="chambre_update", methods={"POST", "GET"})
     */
    public function update(Request $request, Chambre $chambre):Response
    {
        $form = $this->createForm(ChambreType::class,$chambre);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            //dd($chambre);
            $em = $this->getDoctrine()->getManager();
            $em->persist($chambre);
            $em->flush();
            return $this->redirectToRoute('listChambre');
        }
        return $this->render('Chambre/edit.html.twig', ['chambre'=>$chambre, 'form'=>$form->createView()]);
    }
    /**
     * @Route("/update", name="chambre_update_ajx", methods={"POST", "GET"})
     */
    public function updateAjax(Request $request):Response
    {
        if($request->isXmlHttpRequest())
        {
            // $form = $this->createForm(ChambreType::class,$chambre);
            // $form->handleRequest($request);
           $idChambre= $request->request->all()['id'];
            $em = $this->getDoctrine()->getManager();
            $chambre = $em->getRepository(Chambre::class)->find($idChambre);
            if(!$chambre)
            {
                return new JsonResponse(["result"=>'error']);
            }
            $attribut=$request->request->all()['champ'];
            $val=$request->request->all()['val'];
            $chambre->{'set'.ucfirst($attribut)}($val);
            $em->persist($chambre);
            $em->flush();

            // if($form->isSubmitted() && $form->isValid())
            // {
            //     //dd($chambre);
            //     $em = $this->getDoctrine()->getManager();
            //     $em->persist($chambre);
            //     $em->flush();
            //     return $this->redirectToRoute('listChambre');
            // }
            return new JsonResponse(["result"=>$request->request->all()['val']]);
        }
        return new Response('bad request',400);
    }

    /**
     * @Route("/{id<[0-9]+>}/delete", name="chambre_delete")
     */
    public function delete(Chambre $chambre)
    {
            $em = $this->getDoctrine()->getManager();
            $em->remove($chambre);
            $em->flush();
            return $this->redirectToRoute('listChambre');
        
    }


    // public function generateNumeroChambre(ChambreRepository $cham,$numbatimat)
    // {
    //     //$chambre->setNumero(sprintf("%'.03d-", rand(0,999)).$form->get('numero_batimat')->getData());
        
    //     $idLast = $cham->findBy(array(),array('id' => 'DESC'),1 ,0)[0];
    //     $idFormat=str_pad($idLast, 3, '0', STR_PAD_LEFT);
    //     $idBatFormat=str_pad($numbatimat, 3, '0', STR_PAD_LEFT);

    //     return $idFormat."-".$idBatFormat;
    // }
}

templates/chambre/edit.html.twig
{# templates/Chambre/edit.html.twig #}
{% extends "base.html.twig" %}
    {% block title %} Ajouter Chambre {% endblock %}
    {% block body %}
        {{form_start(form,{'attr': {'id': 'form-id','action':'Javascript:void(0)'}})}}
        {{form_widget(form)}}
        <input type="submit" value="valider" class="btn btn-lg btn-warning">
        {{form_end(form)}}
    {% endblock %}

    {% block javascripts %}
    {{ parent() }}
    <script>
        $(document).ready(function(){
            
            $('#form-id').on('submit',function(){
                console.log($('#form-id').serialize());
                $.ajax(
                    {
                    url:"{{path("addChambre")}}",
                    data:$('#form-id').serialize(),
                    method:"POST",
                    success:function(data){                          
                        alert("OK");
                        console.log(data);
                        }
                    }
                )
            })
        })
    </script>
    {% endblock %}

templates/chambre/index.html.twig
{# templates/Etudiant/edit.html.twig #}
{% extends "base.html.twig" %}
    {% block title %} Chambres {% endblock %}
    {% block body %}
    
                <h4 class="text-center">Liste des chambres</h4>
        <table class='table table-hover col-8 offset-2'>
           <thead>
            <tr>
                <th>Numero</th>
                <th>N. Batimat</th>
                <th>Type</th>
            </tr>
            </thead>
            <tbody id="table">
               {# {% for c in chambre %}
                <tr>
                    <td>{{ c.numero }}</td>
                    <td>{{ c.type }}</td>
                    <td>{{ c.numeroBatimat }}</td>
                        <td>
                            <a href="{{ c.id }}/delete">             
                                <img  src="{{asset('images/delete_sweep-24px.svg') }}" alt="-"/>
                            </a>
                        </td>
                        <td>
                            <a href="{{ c.id }}/update">               
                                <img  src="{{asset('images/create-24px.svg') }}" alt="-"/>
                            </a>
                        </td>
                </tr>
                {% endfor %} #}
            </tbody>
        </table>
    <br>
    <br>
    <div class="col justify-content-end pull-bottom position-absolute fixed-bottom">
        <button type="button" id="btn_precedent" name="precedent" value='nav_pre' class="btn_nav btn-sm ubtn float-left">Précédent</button>
        <button type="button" id="btn_suivant" name="suivant" value='nav_suiv' class="btn_nav btn-sm ubtn float-right">Suivant</button>
    </div>
    {% endblock %}

    {% block javascripts %}
    {{ parent() }}
    <script>
        $(document).ready(function(){

    var tab_checkedid={};
    var tab_allId=[];
    let pageEncours=1;
//tab id to remove
    var id_rm=[];
    const tbody=$("#table");
    $('#update_cont').hide();
    sendData(pageEncours);
$('#table').on("click",".select_etu",function(){

  var tab=[]
    if($(this).parents('tr').attr("id"))
    {
        tab = $(this).parents("tr").attr("id").split("_");
        //console.log(tab);
    }
    $('#update_cont').show();
    if($(this).is(':checked'))
    {
            // if($(this).is(":checked"))
            // {
        tab_checkedid[$(this).val()]=$(this).val();
            //updateContUp();
    }else
    {
        delete  tab_checkedid[$(this).val()];
    }
});
$(".select_all").on("change",()=>{
    if($(".select_all").is(":checked"))
    {
       tab_checkedid={};

        for(i in tab_allId)
        {
            tab_checkedid[tab_allId[i]]=tab_allId[i]
        }
        console.log(tab_checkedid);
        $(".select_etu").prop('checked',true);
        $('#update_cont').show();
    }else
    {
        id_rm=[];
        $(".select_etu").prop('checked',false);
        $('#update_cont').hide();
    }
});
//-----------------------------------------------------
//Afficher Montrer la navigation
//--------------------------------------------------
function showhidenav(pageEncours,nbrpage)
{
if(pageEncours===1 || nbrpage===0)
{
    $('#btn_precedent').hide();
}
else
{
    $('#btn_precedent').show();
}
if(nbrpage<=pageEncours)
{

    $('#btn_suivant').hide();
}else
{
    $('#btn_suivant').show();
}
}
//-----------------------------------------------------------



//-------------------------------------------------
//FUNCTION SENDDATA
//-------------------------------------------------
function sendData(offs)
{
    $.ajax({
        type:"POST",
        url:`{{ path('getChambre')}}/${pageEncours}`,
        data:{limit:5,offset:offs},
        dataType:"json",
        success:(data,status)=>{
            console.log(data.chambre);
           // alert(data);
            tbody.html('');
            printData($.parseJSON(data.chambre));
            showhidenav(pageEncours,data.nbrPage)
            pageEncours++;
        }
    });

}
//---------------------------------------------------------
// DELETE FUNCTION
//---------------------------------------------------------
$("#delete_elmt").on('click',function(){
    for(x in tab_checkedid)
    {
        id_rm.push(x);
        $(`#id_${x}`).hide();

    }
    $(".select_all").prop('checked',false);
    $.ajax({
        type:"POST",
        url:`${URL}/chambre/deleteChambre`,
        data:{deleteId:id_rm},
       // dataType:"JSON",
        success:(data,status)=>{
                if(data!=="error")
                {
                    alert("suppression fait avec succes");
                }
                else
                {
                    alert('Erreur lors de la suppression');
                }
        } 
    });

})

$('#btn_suivant').on('click',function(){
    sendData(pageEncours);
});
$('#btn_precedent').on('click',function(){
   pageEncours-= 2;
    sendData(pageEncours);
});
//-------------------------------------------------------------------
// DELETE FUNCTION
//-------------------------------------------------------------------



            function printData(data)
            {
                $.each(data,function(id,cham){
                    tab_allId.push(cham.numero);
                    tbody.append(`
                        <tr id="tr_${cham.id}">
                            <td id="_id_${cham.id}">${cham.numero}</td>
                            <td id="t_numeroBatimat_${cham.id}">${cham.numeroBatimat}</td>
                            <td id="s_type_${cham.id}">${cham.type}</td>
                            <td id="s_supp_${cham.id}"><button class="btn btn-danger"><span class="fa fa-archive"></span></button></td>
                        </tr>

                    `)
                });
            }

//-------------------------------------------------------------------
//
// GESTION DES MODIFICATIONS ET SUPPRESSIONS
//
//-------------------------------------------------------------------
let coul;
let type;
let objEncours=null;
let clone;
let page=1;

        $("#table")
        .on("click","tr",function(){
            coul=$("body").css("background-color");
            $(this).css("background-color","#ff7878");
            $("#table tr").not(this).css("background-color",coul);
        })
        .on("dblclick","td",function(){
            $(this).parents().css("background-color",coul);
            const id = $(this).attr("id");
            const tab=id.split("_");
           // objEncours=$(this);

           type=tab[0];
           clone=$(this).text();

           if((type==='t') || (type==='s'))
           {
               const input = getInput(tab,clone);
               $(this).html(input);
               $(this).children().focus();
           }
        })
        .on("focusout","td",function(e){

            const {id, value}=e.target;
            const tab=id.split("_");
            if(type==='t' || type==='s')
            {
                $(this).html(value);
                const data={
                    "table":"Chambre",
                    "champ":tab[0],
                    "id":tab[1],
                    "val":value
                }
               // console.log(data);
                 //alert("les donnes"+data);
                 updateData(data);
             }
            
        })

        function getInput(tab, txt)
        {
            type=tab[0];
            var input="";
            if(type==="t"){
                input = `<input type="number" id="${tab[1]}_${tab[2]}" value=${txt} />`;
            }
            else if(type==="s")
            {
               // tab_type={"1":"double","2":"individuel"}
                input= `<select id="${tab[1]}_${tab[2]}" >
                    <option value="double">double</option>
                    <option value="individuel">Individuel</option>
                </select>`
            }
           return input;
        }

        //update function

        const updateData=(data)=>{
            $.ajax({
                method:"POST",
                url:"/chambre/update",
                data:data,
                success:function(data){
                    console.log(data);
                    alert('retour du serveur');
                }
            })
        }
            
        })
    </script>
    {% endblock %}